import { Product } from '@/types/product';

export const products: Product[] = [
  {
    id: '1',
    name: 'Kid Tapered Slim Fit Trouser',
    price: 38,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img47.png',
    category: 'kids',
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Men Round Neck Pure Cotton T-shirt',
    price: 64,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png',
    category: 'men',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    isNew: true,
  },
  {
    id: '3',
    name: 'Boy Round Neck Pure Cotton T-shirt',
    price: 60,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png',
    category: 'kids',
    sizes: ['S', 'M', 'L'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Women Zip-Front Relaxed Fit Jacket',
    price: 120,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img35.png',
    category: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    isBestseller: true,
  },
  {
    id: '5',
    name: 'Women Round Neck Cotton Top',
    price: 45,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img2.png',
    category: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    isNew: true,
  },
  {
    id: '6',
    name: 'Men Slim Fit Relaxed Denim Jacket',
    price: 89,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img11.png',
    category: 'men',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
  },
  {
    id: '7',
    name: 'Women Relaxed Fit Jacket',
    price: 110,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img29.png',
    category: 'women',
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
  },
  {
    id: '8',
    name: 'Girls Round Neck Cotton Top',
    price: 35,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img50.png',
    category: 'kids',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    isNew: true,
  },
  {
    id: '9',
    name: 'Men Tapered Fit Flat-Front Trousers',
    price: 75,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img46.png',
    category: 'men',
    sizes: ['30', '32', '34', '36', '38'],
    inStock: true,
  },
  {
    id: '10',
    name: 'Women Zip-Front Relaxed Fit Jacket',
    price: 95,
    image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img31.png',
    category: 'women',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    isBestseller: true,
  },
];